### ISSUE TITLE
README should have instruction on how to combine different parts of iso files

### ISSUE THREAD

**Issue by carriesmi** [manjaro-gnome/download#1]
It is non trivial for a new person to know which files to download from release page and
how to combine them. I had to search for few minutes before I got to correct
I used following command to combine different part and then extracted it normally.
```bash
zip -s- manjaro-gnome-next-20.2.1-unstable-minimal-210129-linux59.iso.zip manjaro-gnome-next-20.2.1-unstable-minimal-210129-linux59.iso.z01 -O output.zip
```
and there may be way to extract without combining first which would be nice.

**Comment by philmmanjaro** [comment]
You can use **engrampa**, **7z** and **file-roller**. Only **Ark** doesn't support it.

**Comment by Chrysostomus** [comment]
Updated readme
