### ISSUE TITLE
file format

### ISSUE THREAD

**Issue by oeyoews** [manjaro-gnome/download#14]
- Is there any difference between xxx.iso.zip and xxx.iso? 
- How can I convert iso.zip into an iso file (because I hope I can download the latest version here every time)

**Comment by idkwuu** [comment]
The ISOs are compressed because of filesize limitations of GitHub ([as noted in the README](https://github.com/manjaro-gnome/download#extracting)). You have to download the .iso.zip and .iso.z01 files, and extract the .zip file, which will give the .iso file.
