### ISSUE TITLE
No builds since 19th January 2022

### ISSUE THREAD

**Issue by bittin** [manjaro-gnome/download#19]

**Comment by Ste74** [comment]
Thank you for reporting
closed via 
https://gitlab.manjaro.org/profiles-and-settings/iso-profiles/-/commit/30f3c2089456410d4706c087590bf05c25ed38e4

**Comment by bittin** [comment]
Great, so can look forward to a new build tomorrow then :)

**Comment by Ste74** [comment]
@bittin I have trigged one manually so wait for a little and you can download one

**Comment by bittin** [comment]
Ah alright thanks :)
