### ISSUE TITLE
[Bug report] Mouse driver does not work properly

### ISSUE THREAD

**Issue by ghost** [manjaro-gnome/download#8]
I installed yesterday's and today's version of Manjaro (manjaro-gnome-next-21.05-development-unstable-minimal-210512-linux510). But the mouse cursor freezes instantaneously after showing the Gnome desktop. The current official version (manjaro-gnome-21.0.4-210506-linux510) does not show this problem.

Any ideas, what I could try?

**Comment by philmmanjaro** [comment]
Well, we have to check **gnome-next** at some point for sure. @Chrysostomus is currently working on a transfer package.
